### ISSUE TITLE
feelpp_fmi_fmu fails to execute bouncing ball example

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1455] opened 2020-03-24 11:02 UTC
On atlas, with the module `feelpp-toolboxes/develop_gcc830_openmpi402` when executing the command line from the [doc](https://github.com/feelpp/feelpp/blob/develop/feelpp/tools/fmi/fmu.adoc#running--a-fmu) the following error happens:
```
/data/scratch/hild/feel/downloads/feelpp_fmi_fmu/fmus/fmi2cs.fmu
F0324 09:18:13.679687 52599 fmumodel2.cpp:88] Check failed: status!=jm_status_error Could not create the DLL loading mechanism(C-API).
*** Check failure stack trace: ***
    @     0x7f131273f38c  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f13148d7dab  Feel::FmuModel2::FmuModel2()
    @     0x7f13148d59d9  _ZN9__gnu_cxx13new_allocatorIN4Feel9FmuModel2EE9constructIS2_JRP17fmi_xml_context_tRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt10shared_ptrI12jm_callbacksEEEEvPT_DpOT0_
    @     0x7f13148d1773  Feel::FMU::load()
    @           0x402ce2  main
    @     0x7f12e6e5b830  __libc_start_main
    @           0x402b89  _start
    @              (nil)  (unknown)
[1]    52599 abort (core dumped)  feelpp_fmi_fmu
```

**Comment by prudhomm** [comment] 2020-03-26 08:08
it seems to be indeed a problem on atlas. it get this:

![Uploading Screenshot 2020-03-26 09.07.00.png…]()

**Comment by romainhild** [comment] 2020-03-26 08:11
but can you reproduce it on atlas ? or is it a problem on my end ?

**Comment by prudhomm** [comment] 2020-03-26 09:43
I cannot reproduce on my end but I haven't tried on atlas, it seems that loading the shared lib failed

**Comment by vincentchabannes** [comment] 2020-03-27 08:50
@prudhomm @romainhild in testsuite, feelpp_test_fmi seems works on my side on atlas (no error with ctest). I don't know if the test is representative of your isssue. (I re-enable this test in testsuite with 21c2a7ed3f7cf800c8c338bdf834ebe94a01db34)

**Comment by romainhild** [comment] 2020-03-27 12:51
Indeed in the testsuite there is no problem, but I have compiled both the test and the tool, and I still have the problem with the tool.
If I look into what is in the testsuite testcase, we have all these files: fmi2cs.fmu  fmi2cs.libs  fmi2cs.log  fmi2cs_FMU.libs  fmi2cs_FMU.log  fmi2cs_FMU.makefile  fmi2cs_info.json  fmi2cs_tofmu.mos
but in the tools example, we download from girder only fmi2cs.fmu, isn't it a problem ?

**Comment by prudhomm** [comment] 2020-03-27 12:59
why should it be a problem?

**Comment by romainhild** [comment] 2020-03-27 13:04
I don't know.
Also if I try to use the fmu from the testsuite with the tool, I got a different error:
```
./feelpp_fmi_fmu --fmu.filename ../../../testsuite/feelfmi/fmi2cs/fmi2cs.fmu
[ Starting Feel++ ] application feelpp_fmi_fmu version 0.1 date 2020-Mar-27
 . feelpp_fmi_fmu files are stored in /data/scratch/hild/feel/feelpp_fmi_fmu/np_1
 .. logfiles :/data/scratch/hild/feel/feelpp_fmi_fmu/np_1/logs
F0327 13:45:43.223199 31576 fmu.cpp:62] Check failed: version != fmi_version_unknown_enu The FMU version could not be determined. Unpacking of FMU ../../../testsuite/feelfmi/fmi2cs/fmi2cs.fmu into /data/s
cratch/hild/feel/feelpp_fmi_fmu/np_1/fmu_tmpdir/ failed
```

**Comment by vincentchabannes** [comment] 2020-03-27 13:57
@romainhild the issue is just that you need to put the absolute path, not relative : 
```
./feelpp/tools/fmi/feelpp_fmi_fmu  --fmu.filename /ssd/chabannes/Feelpp/feelpp.build_release/testsuite/feelfmi/fmi2cs/fmi2cs.fmu 
[ Starting Feel++ ] application feelpp_fmi_fmu version 0.1 date 2020-Mar-27
 . feelpp_fmi_fmu files are stored in /home/u2/chabannes/feel/feelpp_fmi_fmu/np_1
 .. logfiles :/home/u2/chabannes/feel/feelpp_fmi_fmu/np_1/logs
FMU Model loaded : name=BouncingBall, guid={325b64ac-094c-43f5-a14b-4682c9cbccc0}, kind=CS, id=fmi2cs
Version returned from FMU = 2.0
=================================================================
FMU Model BouncingBall : list of variables
=================================================================
Name                          Alias Type      Description
_D_whenCondition1             0     bool      
der(h)                        0     double    der(Height)
der(v)                        0     double    der(Velocity)
e                             0     double    Coefficient of restitution
h                             0     double    Height
h0                            0     double    Initial height
v                             0     double    Velocity
=================================================================
stdout            | info    | The initialization finished successfully without homotopy method.
rm: cannot remove '/home/u2/chabannes/feel/feelpp_fmi_fmu/np_1/fmu_tmpdir/binaries/linux64': Directory not empty
[env] Time : 1.89937s
[ Stopping Feel++ ] application feelpp_fmi_fmu execution time 1.89937s
```

**Comment by romainhild** [comment] 2020-03-27 14:16
ok indeed, so what is the difference between the fmu from the testsuite and the one on girder ?

**Comment by vincentchabannes** [comment] 2020-03-27 14:23
maybe the openmodelica version used for generated the fmu. I remember that @lsala had troubles with some versions of openmodelica.

**Comment by lsala** [comment] 2020-03-27 14:25
When I was using it, the latest version of OpenModelica (1.13?) had failed (don't know why) so I had to use the previous one (1.12 if I remember correctly)

**Comment by prudhomm** [comment] 2020-03-27 14:34
I use 
```
omc --version
OpenModelica 1.15.0~dev-46-g9d99fda
```

so far so good. I generated the fmu with a recent version without problem

**Comment by prudhomm** [comment] 2020-03-27 14:35
the one on girder is the one I generated. in the testsuite it is generated on atlas via omc

**Comment by romainhild** [comment] 2020-03-27 14:38
on atlas, it is 1.12
Maybe there is a break in the compatibility after version 1.12 ?

**Comment by prudhomm** [comment] 2020-04-07 10:00
@romainhild do you still have an issue here ?

**Comment by romainhild** [comment] 2020-04-07 10:29
yes, to reproduce, login into atlas and do:
```
module purge
module load feelpp-quickstart/develop_gcc830_openmpi402
feelpp_fmi_fmu --config-file="github:{repo:feelpp,path:feelpp/tools/fmi/fmus/bouncingball.cfg}"
```

**Comment by prudhomm** [comment] 2020-04-07 10:44
so all good, I close it

**Comment by romainhild** [comment] 2020-04-07 10:46
sorry, yes I still have the issue, so no it can't be closed

**Comment by prudhomm** [comment] 2020-04-07 11:08
And it works for @vincentchabannes?

**Comment by romainhild** [comment] 2020-04-07 11:09
the fmu from the testsuite works, not the one on girder

**Comment by vincentchabannes** [comment] 2020-04-07 11:09
it works only if the fmu is generated on atlas, not with the one on girder

**Comment by prudhomm** [comment] 2020-08-27 18:30
We have dymola now. Let's see what if the fmu are truly portable on Linux

**Comment by prudhomm** [comment] 2020-08-27 18:31
feelpp/hygrothermie#15

**Comment by prudhomm** [comment] 2020-08-30 12:45
@romainhild we run fmu with the option `--nochdir` with eg  `feelpp_fmi_fmu` otherwise we get a cryptic error message regarding the version not being accessible. Let me know how it goes on atlas.

**Closed** 2021-10-15 13:17 UTC
Labels: platform:atlas, type:fte, status:can-not-reproduce, module:fmi
