### ISSUE TITLE
loadMesh behaviour when msh filename is wrong

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#668] opened 2015-10-02 11:04 UTC
When trying to use loadMesh I end up having problems because of misspelling in the msh filename.
In fact, as far as I know, when no msh file or wrong filename is given loadMesh create a "default mesh"... hence my problems.

Would it be possible to issue a clear message when running loadMesh for the unexperienced user (like me) that warns about not finding the requested filename and using instead the "defaut mesh"?

**Comment by vhuber** [comment] 2015-10-05 07:24
I guess it won't change anything passing [the `LOG(WARNING)`](https://github.com/feelpp/feelpp/blob/develop/feel/feelfilters/loadmesh.hpp#L177) to a `std::cerr`, isn't it ?

**Comment by prudhomm** [comment] 2015-10-05 10:54
@Trophime @vhuber indeed there is a warning that is in the log file but I guess you want to have it on screen ?

**Comment by Doyeux** [comment] 2016-05-30 08:00
Same kind of remark than @Trophime. When I set the path to the mesh to a wroing value, the default one is loaded (which is very light), and the application runs and crashes much later on (when it need to iterate on faces which do not exist for example).
Is there a way to know in the code if the defaut mesh is loaded ? Either a return code to loadMesh or a environment function Environment::loadedMeshIsDefault() ?
That case developers could do if they want:
CHECK( isDefaultMesh ), "something is wrong, the default mesh is loaded";

**Comment by prudhomm** [comment] 2016-05-30 08:09
@Doyeux it should not be the job of Environment.
However now a message with the loaded mesh is printed on screen when you use `loadMesh()` 
could you show a reproducer ?

**Comment by Doyeux** [comment] 2016-05-30 08:17
yes I got the message. It's just that I wanted my application to stop if the mesh doesn't exists, because sometimes it continues for a long time and crashed for example when trying to solve a linear problem assembled incorrectly (which is normal since the markers needed are not present on the default mesh).
The log is very verbose and I have to think about going to the very beginning for an error that I could have captured in my code right after loadMesh.
But I guess a good workaround would be to do:
```c++
std::string meshFileName;
CHECK(! Environment::findFile(meshFileName).empty() ), "the mesh file is not found";
loadMesh(meshFileName);
```
I'll do that.

**Comment by prudhomm** [comment] 2016-05-30 08:33
yes, the default mesh (hypercube.geo/msh) is not a replacement for the user to verify that the mesh filename is correct.

**Comment by prudhomm** [comment] 2016-05-30 08:33
I close this issue

**Closed by prudhomm** 2016-05-30 08:33 UTC
Labels: module:mesh, type:feature
