### ISSUE TITLE
FTBS with gcc 8.1 on Debian/testing

### ISSUE THREAD

**Issue by Trophime** [feelpp/feelpp#1167] opened 2018-05-21 14:53 UTC
for the record:
```
/home/LNCMI-G/trophime/feelpp/feel/feeldiscr/doftable.hpp: In member function ‘const vector_indices_type& Feel::DofTable<MeshType, FEType, PeriodicityType, MortarType>::localToGlobalIndices() const’:
/home/LNCMI-G/trophime/feelpp/feel/feeldiscr/doftable.hpp:718:20: error: invalid initialization of reference of type ‘const vector_indices_type&’ {aka ‘const std::vector<Eigen::Matrix<int, -1, 1>, Eigen::aligned_allocator<Eigen::Matrix<int, -1, 1> > >&’} from expression of type ‘const vector_indices_type’ {aka ‘const std::unordered_map<long unsigned int, Eigen::Matrix<int, -1, 1>, std::hash<long unsigned int>, std::equal_to<long unsigned int>, Eigen::aligned_allocator<std::pair<const long unsigned int, Eigen::Matrix<int, -1, 1> > > >’}
             return M_locglob_indices;
                    ^~~~~~~~~~~~~~~~~
feel/CMakeFiles/feelpp.dir/build.make:897: recipe for target 'feel/CMakeFiles/feelpp.dir/feeldiscr/stencil.cpp.o' failed
make[2]: *** [feel/CMakeFiles/feelpp.dir/feeldiscr/stencil.cpp.o] Error 1
make[2]: Leaving directory '/home/LNCMI-G/trophime/feelpp_build/gcc-8'
```

**Comment by prudhomm** [comment] 2018-05-21 15:49
this is a duplicate of #1152. Currently Feel++ fails to compile with GCC 6 7 and 8 it seems

**Comment by Trophime** [comment] 2018-05-22 16:20
yep but the error messages are quite different no?
In #1152, feelpp was compiling fine except for the HDG part
here the basic "make " does not compile...

**Closed** 2018-07-01 06:31 UTC
Labels: platform:debian, status:duplicate, type:ftbs
