### ISSUE TITLE
Singularity images fail to build

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#1075] opened 2017-10-13 03:54 UTC
No space left on device

https://buildkite.com/feelpp/feelpp-singularity/builds/108#a459877b-9d45-40e4-8c22-da836516ef0e

**Comment by gdolle** [comment] 2017-10-13 09:41
The problem comes from docker. 
With singularity 2.4, I should be able to resolve this issue by not having to pull docker images beforehands in order to calculate image size (it will be far nicer). Moreover, with squashfs feature, we should economize some space 👍 
I'll do that as soon as possible.

**Comment by gdolle** [comment] 2017-10-16 13:23
I close this issue as duplicate of #1044 (Other remarks to this issue)

**Closed by gdolle** 2017-10-16 13:23 UTC
Labels: module:build, type:ftbs
