### ISSUE TITLE
Problems when linking Feel++ develop version

### ISSUE THREAD

**Issue by grabbitnu** [feelpp/feelpp#494] opened 2014-12-31 02:23 UTC
Hi, 
I cloned a develop version from github by
git clone https://github.com/feelpp/feelpp
I used the following configurations to compile Feel++ but failed when linking HDF5:
Ubuntu 14.04
cmake 3.1.0
boost 1.54
clang 3.4
libhdf5-openmpi-dev 1.8.11-5
gmsh 2.8.3
libpetsc3.4.2-dev
nlopt 2.4.1

Options:
FEELPP_ENABLE_HDF5    ON
HDF5_CXX_COMPILER_EXECUTABLE     /usr/bin/h5c++                                                                                                                                                                    
 HDF5_C_COMPILER_EXECUTABLE       /usr/bin/h5cc                                                                                                                                                                     
 HDF5_C_INCLUDE_DIR               /usr/include                                                                                                                                                                      
 HDF5_DIFF_EXECUTABLE             HDF5_DIFF_EXECUTABLE-NOTFOUND                                                                                                                                                     
 HDF5_DIR                         HDF5_DIR-NOTFOUND                                                                                                                                                                 
 HDF5_Fortran_COMPILER_EXECUTAB   /usr/bin/h5fc                                                                                                                                                                     
 HDF5_IS_PARALLEL                 ON                                                                                                                                                                                
 HDF5_dl_LIBRARY_DEBUG            HDF5_dl_LIBRARY_DEBUG-NOTFOUND                                                                                                                                                    
 HDF5_dl_LIBRARY_RELEASE          /usr/lib/x86_64-linux-gnu/libdl.so                                                                                                                                                
 HDF5_hdf5_LIBRARY_DEBUG          HDF5_hdf5_LIBRARY_DEBUG-NOTFOUND                                                                                                                                                  
 HDF5_hdf5_LIBRARY_RELEASE        /usr/lib/x86_64-linux-gnu/libhdf5.so                                                                                                                                              
 HDF5_m_LIBRARY_DEBUG             HDF5_m_LIBRARY_DEBUG-NOTFOUND                                                                                                                                                     
 HDF5_m_LIBRARY_RELEASE           /usr/lib/x86_64-linux-gnu/libm.so                                                                                                                                                 
 HDF5_pthread_LIBRARY_DEBUG       HDF5_pthread_LIBRARY_DEBUG-NOTFOUND                                                                                                                                               
 HDF5_pthread_LIBRARY_RELEASE     /usr/lib/x86_64-linux-gnu/libpthread.so                                                                                                                                           
 HDF5_z_LIBRARY_DEBUG             HDF5_z_LIBRARY_DEBUG-NOTFOUND                                                                                                                                                     
 HDF5_z_LIBRARY_RELEASE           /usr/lib/x86_64-linux-gnu/libz.so

The following script is used to build Feel++:
cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -DCMAKE_C_COMPILER=/usr/bin/clang \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DNLOPT_INCLUDE_DIR=/usr/include \
    -DNLOPT_LIBRARY=/usr/lib/x86_64-linux-gnu/libnlopt.so \
    -DFEELPP_ENABLE_VTK=OFF \
    -DFEELPP_ENABLE_DOXYGEN=OFF \
    -DCMAKE_INSTALL_PREFIX=/home/zhenyu/deps \
    ../feelpp/

when we run 'make -j8', finally the building procedure is broken with following errors:
...
[ 90%] Built target feelpp_tut_loadmesh
Scanning dependencies of target feelpp_tut_mylaplacian
[ 90%] Building CXX object doc/manual/tutorial/CMakeFiles/feelpp_tut_mylaplacian.dir/mylaplacian.cpp.o
Linking CXX executable feelpp_tut_geotool
/usr/bin/ld: warning: libcholmod.so.2.1.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libcholmod.so.3.1.0
/usr/bin/ld: warning: libcholmod.so.2.1.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libcholmod.so.3.1.0
/usr/bin/ld: warning: libcholmod.so.2.1.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libcholmod.so.3.1.0
/usr/bin/ld: warning: libumfpack.so.5.6.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libumfpack.so.3.1.0
/usr/bin/ld: warning: libumfpack.so.5.6.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libumfpack.so.3.1.0
/usr/bin/ld: warning: libumfpack.so.5.6.2, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libumfpack.so.3.1.0
/usr/bin/ld: warning: libamd.so.2.3.1, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libamd.so.3.1.0
/usr/bin/ld: warning: libamd.so.2.3.1, needed by /usr/lib/slepc/linux-gnu-c-opt/lib/libslepc.so, may conflict with libamd.so.3.1.0
/usr/bin/ld: warning: libmetis.so.3.1, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../libcholmod.so, may conflict with libmetis.so.5
/usr/bin/ld: warning: libmetis.so.3.1, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../libcholmod.so, may conflict with libmetis.so.5
/usr/bin/ld: warning: libmetis.so.3.1, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../libcholmod.so, may conflict with libmetis.so.5
/usr/bin/ld: warning: libmetis.so.3.1, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../libcholmod.so, may conflict with libmetis.so.5
/usr/bin/ld: warning: libcolamd.so.2.8.0, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libglpk.so, may conflict with libcolamd.so.3.1.0
/usr/bin/ld: warning: libcolamd.so.2.8.0, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libglpk.so, may conflict with libcolamd.so.3.1.0
/usr/bin/ld: CMakeFiles/feelpp_tut_geotool.dir/geotool.cpp.o: undefined reference to symbol 'H5open'
//usr/lib/x86_64-linux-gnu/libhdf5.so.7: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [doc/manual/tutorial/feelpp_tut_geotool] Error 1
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_geotool.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cmake[2]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_mylaplacian.dir/mylaplacian.cpp.o] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_mylaplacian.dir/all] Interrupt
make[2]: *** make[2]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myexporter.dir/myexporter.cpp.o] Interrupt
wait: No child processes.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myexporter.dir/all] Interrupt
make[2]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myadvection.dir/myadvection.cpp.o] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myintegrals.dir/all] Error 2
make[2]: *** wait: No child processes.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** make[2]: wait: No child processes.  Stop.
*** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myfunctor.dir/myfunctor.cpp.o] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myadvection.dir/all] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myfunctor.dir/all] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_myfunctionspace.dir/all] Error 2
make[2]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_mybackend.dir/mybackend.cpp.o] Interrupt
make[1]: *** [doc/manual/tutorial/CMakeFiles/feelpp_tut_mybackend.dir/all] Interrupt
make: *** [all] Interrupt

It seems the libhdf5 library can not be properly linked. But up to now I have no idea about the correct treatment. You'll be highly appreciated for any suggestion and hints.

Cheers,
Zhenyu Zhang
zyzhang@nuaa.edu.cn

**Comment by prudhomm** [comment] 2015-01-03 12:47
@aancel could you have a look please ?

**Comment by prudhomm** [comment] 2015-01-03 12:48
@grabbitnu I use also 14.04 and I have no such issue. it compiles like a charm.

**Comment by grabbitnu** [comment] 2015-01-04 00:29
I suppose the cmake compiler can not find libhdf5-openmpi-dev in Ubuntu. So not an idea yet. Any hints are welcome!

**Comment by aancel** [comment] 2015-01-05 14:20
@grabbitnu I tested your setup with the 14.04 ubuntu. The package that I installed are the following ones:
"cmake", "libboost1.54-all-dev", "clang-3.4", "libhdf5-openmpi-dev", "gmsh", "libpetsc3.4.2-dev", "nlopt-dev", "automake", "libreadline-dev", "flex", "bison", "libgmsh-dev"

BTW, Did you compiled cmake from the source code ? 
The latest version of cmake available on this version of ubuntu is the 2.8.12 apparently and you used 3.1.0.
I then used your command line for the cmake step, and then tried to build with make. Everything was built without any errors on my side.

Apparently the error is caused by a symbol not found in the hdf5 library: "H5open".
- Can you check that the library is used in the link step ? (with make -j8 VERBOSE=1)
- Can you check that the symbol is present in the library linked and that the possible symlinks are ok ? (use "nm -a libfile.so | grep H5open" to check for the missing symbol)

**Comment by aancel** [comment] 2015-02-11 09:42
@grabbitnu Is your issue solved ? Can we clone this issue ?

**Comment by vhuber** [comment] 2015-03-30 13:41
Without news on that issue, I close it.

**Closed by vhuber** 2015-03-30 13:41 UTC
Labels: status:investigate
